### ISSUE TITLE
 Windows Compatibility - File Name Issue

### ISSUE THREAD

**Issue by KevinRohn** [graphlit/graphlit-samples#19]
# Description

When attempting to check out the repository on Windows systems, the following error occurs:

```
error: invalid path 'python/streamlit-multipage-chat-azure-blob-feed/pages/9_Need_Help?.py'
fatal: unable to checkout working tree
```

## Issue
Some files contains a question mark (?), which is a restricted character in Windows filesystems. Windows does not allow the following characters in file names: ` \ / : * ? " < > |`

Maybe do change this, to allow more local developers to use this sample repository. I usually work on a MacBook, but sometimes im forced to work on windows, so it is not a great experience for starters ;)

**Comment by kirk-marple** [comment]
Good point, Streamlit uses the file name for displaying in the menu, and we'd developed these using WSL2 on Windows.

I'll see if there's a better way to handle that.

**Comment by kirk-marple** [comment]
Now fixed, just removed the ? from the filenames.
