### ISSUE TITLE
URL not working

### ISSUE THREAD

**Issue by faisal-abdin90** [graphlit/graphlit-samples#3]
The URL that I paste is not being picked up by the app.

The PPTX and PDF files URLs that I pasted are all shared publicly.

I have tried links from both GoogleDrive and OneDrive.

I am not sure what the error message means as well (attached)
![image](https://github.com/graphlit/graphlit-samples/assets/123160543/4d8cdc59-6f43-4a74-92ab-a81228455b6f)

I don't see an option to upload the files directly as well.

**Comment by kirk-marple** [comment]
Sorry for the delayed reply.

We've updated the sample apps, and now have one where you can upload multiple files:
https://graphlit-samples-chat-file-citations.streamlit.app/

And a newer version of the 'chat with PDF':
https://graphlit-samples-chat-pdf.streamlit.app/

There had been an issue with inferring the content type from the URI, for cases where the MIME type was not being reported properly.  So, it was treating the URI as a webpage, not a file.  This can happen if the link requires authentication.

If you still see any issues with the new sample apps, please let us know, and provide the URI you are trying.
